name: "Deploy gcpquickstart"

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

env:
  ART_MIDGARD_SERVER: midgard.pp.argonaut.live
  ART_FRONTEGG_SERVER: argonaut-pp.frontegg.com


jobs:
  build:
    
    environment: 
      name: prgcpenvv 
    
    runs-on: ubuntu-latest
    name: Build and Push Img
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download art
        run: |
          curl --silent https://github.com/argonautdev/public/releases/download/v0.11.0-alpha.5/art-linux -L -o art
          chmod +x ./art
          mv ./art /usr/local/bin/art
      - name: Fetch BuildTime Secrets
        run: |
          art configure --key ${{ secrets.dev_ART_KEY }} --secret ${{ secrets.dev_ART_SECRET }}
          art app envvars get -f .art/argonaut-gcpdemob-gcpquickstart.yaml \
            --set appName="gcpquickstart" \
            --set argonaut.env="prgcpenvv" \
            --set argonaut.region="us-west1" \
            --set argonaut.cluster="gketestf" \
            --set argonaut.serviceType="stateless" \
            --set argonaut.imageRegistry="gcptestfdockerio" \
            --type buildtime \
            --format dotenv > art-build-secrets.env
          echo 'ART_BUILD_SECRETS_FILE<<EOF' >> $GITHUB_ENV
          cat art-build-secrets.env >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Login to Github container repo
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: prashantraj18198
          password: ${{ secrets.ARG_gcptestfdockerio_ACCESS_TOKEN }}
      - name: Build Image and Push
        uses: docker/build-push-action@v2
        id: build-push
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ${{ env.ART_BUILD_SECRETS_FILE }}
          tags: docker.io/prashantraj18198/gcpquickstart-prgcpenvv:${{ steps.get_sha.outputs.SHA_SHORT }}
          cache-from: type=registry,ref=docker.io/prashantraj18198/gcpquickstart-prgcpenvv:buildcache
          cache-to: type=registry,ref=docker.io/prashantraj18198/gcpquickstart-prgcpenvv:buildcache,mode=max

  deploy:
    
    environment: 
      name: prgcpenvv 
    
    runs-on: ubuntu-latest
    name: Deploy to Argonaut
    needs: build
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Fetch branch name
        shell: bash
        run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/heads/}
        id: get_branch_name
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - name: Download art
        run: curl --silent https://github.com/argonautdev/public/releases/download/v0.11.0-alpha.5/art-linux -L -o art
      - name: Configure art
        run: |
          chmod +x ./art
          sudo mv ./art /usr/local/bin/art
          art configure --key ${{ secrets.dev_ART_KEY }} --secret ${{ secrets.dev_ART_SECRET }}
          art app deploy -f .art/argonaut-gcpdemob-gcpquickstart.yaml \
            --set image="docker.io/prashantraj18198/gcpquickstart-prgcpenvv" \
            --set 'labels.argonaut\.dev/git-provider'='github' \
            --set argonaut.git-provider='github' \
            --set imageTag="${{ steps.get_sha.outputs.SHA_SHORT }}" \
            --set appName="gcpquickstart" \
            --set argonaut.env="prgcpenvv" \
            --set argonaut.region="us-west1" \
            --set argonaut.cluster="gketestf" \
            --set argonaut.serviceType="stateless" \
            --set argonaut.imageRegistry="gcptestfdockerio" 